### ISSUE TITLE
Docker download

### ISSUE THREAD

**Issue by choughton21** [mikeizbicki/cmc-csci143#10]
I was wondering if you might be able to help with the error I am getting with the Docker download, it is saying I do not have access to enough memory, and when I asked how much memory I have to the computer with, du -s, it says only 116M.  Is there a certain file I should be storing to that has more memory? 

lambda-server:~ $ curl -fsSL https://get.docker.com/rootless | sh
# Installing stable version 20.10.3
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 65.7M  100 65.7M    0     0  62.9M      0  0:00:01  0:00:01 --:--:-- 62.9M
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 19.0M  100 19.0M    0     0  48.9M      0 --:--:-- --:--:-- --:--:-- 48.9M
tar: dockerd: Wrote only 512 of 10240 bytes
tar: docker-init: Cannot write: Disk quota exceeded
tar: docker-proxy: Cannot write: Disk quota exceeded
tar: containerd-shim-runc-v2: Cannot write: Disk quota exceeded
tar: containerd-shim: Cannot write: Disk quota exceeded
tar: containerd: Cannot write: Disk quota exceeded
tar: Exiting with failure status due to previous errors

**Comment by mikeizbicki** [comment]
It's a little bit hard to read the output of your install command.  In the future, if you put it in triple backticks
```
you'll get a code block like this
```
and it will be easier to read.

The crux of the issue is this line:
```
tar: containerd: Cannot write: Disk quota exceeded
```
The problem is that you've already used up 11G of disk space on the account.  You shouldn't need to be using that much disk space at this point, so you'll have to delete some of your folders/files that are using too much.  See my answer to #8 to find which folders are taking up too much space.
