### ISSUE TITLE
Problems running container

### ISSUE THREAD

**Issue by edwardwu11** [mikeizbicki/cmc-csci143#108]
Hi Mike,

I hope you are doing well. After building a Docker image, I'm having problems running it. I tried running
```
docker run -d -p {UID}:5000 flask-tutorial
```
but I'm getting an error message that says
```
631992ea3126efa1999051efad6c7d061a8645ef6c12a6e669caeff887ab397e
docker: Error response from daemon: driver failed programming external connectivity on endpoint trusting_fermi (fb782bc926ec9999757f799cb093c0b7130efde71f0825e96dcb1ef2cd5d82ae): fork/exec /home/{username}/bin/rootlesskit-docker-proxy: no such file or directory.
```
I'm not sure how I can fix this error.

**Comment by iamasteriix** [comment]
Could you go through the process you used to create this image?

Also, what are the commands in your `Dockerfile` file? And would you happen to have a `docker-compose.yml` by any chance?

**Comment by edwardwu11** [comment]
I just followed the instructions of the tutorial by making a directory called ```flaskweb```. Cd'ing into that directory and creating the ```app.py``` file with the same contents as the tutorial. The contents in my Dockerfile are:
```
  1 FROM ubuntu:16.04
  2
  3 RUN apt-get update -y && \
  4     apt-get install -y python3-pip python3-dev
  5
  6 # We copy just the requirements.txt first to leverage Docker cache
  7 COPY ./requirements.txt /app/requirements.txt
  8
  9 WORKDIR /app
 10
 11 RUN pip3 install -r requirements.txt
 12
 13 COPY . /app
 14
 15 ENTRYPOINT [ "python" ]
 16
 17 CMD [ "app.py" ]
```
I don't have a ```docker-compose.yml```.

**Comment by iamasteriix** [comment]
I think you need to add the `.local/` directory to `ExecStart` in your `docker.service` if you moved your bin file into said directory. Open `docker.service` as in `.config/systemd/user/docker.service` and make sure the variable is set to
```
ExecStart=/home/username/.local/bin/dockerd-rootless.sh
```

**Comment by edwardwu11** [comment]
After following your steps @ceejay-el, and running
```
docker run -d -p {UID}:5000 flask-tutorial
```
I'm still getting a similar error:
``` 

bdd12b20e6b9c8234d60b0a6ab271650fe1afdb0de75014569fee1ce4d419525
docker: Error response from daemon: driver failed programming external connectivity on endpoint hardcore_payne (7375c0fc83085d81a40cb89a0b9e2c1a39ef8edaec7b3109a2fdb036104b17dd): fork/exec /home/username/bin/rootlesskit-docker-proxy: no such file or directory.
```

**Comment by iamasteriix** [comment]
That's strange. The error `fork/exec /home/username/bin/rootlesskit-docker-proxy: no such file or directory` indicates that docker cannot find the file in that directory. Did you restart docker after you moved stuff around?

I would recommend running the command `lsb_release -d` and change your ubuntu image version to whatever it returns (should be `ubuntu:18.04`). Also, I'm not sure how big of a deal this is so you can skip it, but try changing the entrypoint to `python3`, since everything else is set to that in your `Dockerfile`.

After that, you should `systemctl --user stop docker` then `systemctl --user start docker`, then see if that helps with anything.
