### ISSUE TITLE
example3.sh: line 42: dir/$file: ambiguous redirect

### ISSUE THREAD

**Issue by dustin-lind** [mikeizbicki/cmc-csci143#111]
Hi @mikeizbicki,

I'm getting the following error after running `bash example3.sh`:
```
problem 4
example3.sh: line 42: dir/$file: ambiguous redirect
````
This causes me to be unable to check my answers for 4, 5, and 6 of `example3.sh`

Line 42 is
```
for file in 'a b' "c d"; do echo 'hello world' > dir/$file; done
```

Did you intend to cause this error? If so, how are we supposed to handle a problem like this on tomorrow's quiz?

Best,

Dustin

**Comment by mikeizbicki** [comment]
The `exampleX.sh` files are intended to be run with the `sh` command and not the `bash` command.  Notice the shebang:
```
$ head -n1 example3.sh 
#!/bin/sh
$ ./example3.sh
/tmp/tmp.CqEYpHII1N
problem 1
4
problem 2
4
problem 3
1
problem 4
2
problem 5
3
problem 6
2
```
Recall that tn the lambda server `sh` redirects to the `dash` shell:
```
$ which sh
/bin/sh
$ ls -l /bin/sh
lrwxrwxrwx 1 root root 4 Aug 19  2019 /bin/sh -> dash
```
which is a minimally POSIX-compliant shell, and the one you should be in the habit of using for all scripts. `bash`'s primary useage is for interactive terminal sessions rather than inside scripts.  In this case, the error message `bash` is giving is basically saying the script file is doing something really stupid (not putting quotes around the variables) and so throwing an error.  That stupidity is intentional, though, for the sake of the quiz.
