### ISSUE TITLE
Problems uploading media to finished app

### ISSUE THREAD

**Issue by axelahdritz** [mikeizbicki/cmc-csci143#119]
Hey! 

I am not sure if others are experiencing the same problem, but I am having an issue uploading images to my finished flask-on-docker application. Whenever I "browse" my directory and pick out an image from my Desktop for upload, I encounter an `Internal Server Error` on my browser (no error messages in my terminal though) with:

`The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.` 

My development docker container was also experiencing problems uploading a photo, shooting me a "File not Found" error due to the photo not lying in the `/usr/src/app/project/media/` directory. I was wondering whether I need to put my photo somewhere in the lambda server before uploading it? Or is there an error in my application (or port configurations) that is stopping this form of local uploads?

Sorry for the vague questions, I am not sure what is going on here and have looked over my code to find bugs but can't seem to locate the issue.

Any insights would be wonderful. Thanks!

**Comment by mikeizbicki** [comment]
An internal server error means that there is an error in you python code.  You need to look at the logs of your flask web server in order to figure out what the error is.  To get the logs, run
```
$ docker-compose logs -f
```
Then connect to the webserver from firefox.  You should see python barf (yes, this is the technical term) out a stack trace that you can use to figure out what the python error is.

---

PS.  Code/errors that has multiple lines or is on a line by itself should be in a code block (triple backticks) and not inline code (single backticks).

**Comment by axelahdritz** [comment]
Thank you! I traced the error down to the `__init__.py` file and realized that I forgot to add a media folder :/
