### ISSUE TITLE
Port forwarding issue

### ISSUE THREAD

**Issue by afzal-p** [mikeizbicki/cmc-csci143#12]
When I run the command:
`docker run -d -p 5998:5002 flask_image`

I receive the error:

```
docker: Error response from daemon: driver failed programming external connectivity on endpoint peaceful_ishizaka (04aaac09a8ed7ad7443ce6389a80f7559d70cdab46bf808da19202c02ce22489): fork/exec /home/afzal.patel/bin/rootlesskit-docker-proxy: no such file or directory.
```

Any suggestions?

**Comment by mikeizbicki** [comment]
I see two problems:

1. you are using port 5002 instead of port 5000 on your `docker run` command

1. docker is looking for the `rootlesskit-docker-proxy` program in your `$HOME/bin` folder, but I can see that you don't have this folder and have moved the executeables to `$HOME/.local/bin`.  Somehow, you need to get docker to be able to find the this binary, either by adjusting your `$PATH` or moving the files.

**Comment by afzal-p** [comment]
Thank you, I could not fix this by adjusting the path variable, but it worked when I moved the files back to $HOME/bin

**Comment by CurtisSalinger** [comment]
Hello @mikeizbicki I am having this same issue, where I am seeing `/home/Curtis.Salinger.22/bin/rootlesskit-docker-proxy: no such file or directory.`. I am receiving this because I moved all of the bin files from the home folder to my `.local/bin` folder.

I was searching how to change the path that docker uses to find `rootlesskit-docker-proxy` and was wondering if you could point me to a resource to do so. I believe as we were about to cover changing the path in our Friday lecture, we ran into the glitch that when you exited and logged back on, docker still ran, so we did not end up changing the docker path to search for `.local/bin`
