### ISSUE TITLE
Changing Docker $PATH

### ISSUE THREAD

**Issue by CurtisSalinger** [mikeizbicki/cmc-csci143#13]
Referring to your comment on closed issue #12 :

"docker is looking for the `rootlesskit-docker-proxy` program in your `$HOME/bin` folder, but I can see that you don't have this folder and have moved the executeables to `$HOME/.local/bin`.  Somehow, you need to get docker to be able to find the this binary, either by adjusting your `$PATH` or moving the files."

I was searching how to change the path that docker uses to find `rootlesskit-docker-proxy` and the other necessary files that I moved to my `.local/bin/` and was wondering if you could point me to a resource to do so. I believe as we were about to cover changing the path in our Friday lecture, we ran into the glitch that when you exited and logged back onto the server, docker still ran, so we did not end up changing the docker path to search for `.local/bin`. I recognize I could move my bin file back to the home directory to solve this, but am hoping to use the *elegant* solution. Thanks!

**Comment by chenpatrickc** [comment]
Here's a step-by-step guide that worked for me:

This references the discussion on issue #7.

1. Stop the docker daemon with `systemctl --user stop docker`
2. Open the `docker.service` file with `vim .config/systemd/user/docker.service`
3. Change the `ExecStart` variable to `/home/$USER/.local/bin/dockerd-rootless.sh`. Either `$USER` or your actual username should work fine.
4. `systemctl --user daemon-reload` to reload units since a source config file was changed.
5. Start the docker daemon `systemctl --user start docker`

This should allow docker to find all your files in `.local/bin`

**Comment by CurtisSalinger** [comment]
@chenpatrickc 
Thanks a bunch! This fixed it for me.
