### ISSUE TITLE
Why do I have to continuously put a personal access token (PAT) as a password in Git when pushing? 

### ISSUE THREAD

**Issue by vbopardi** [mikeizbicki/cmc-csci143#134]
I pushed to github twice for pagilaHW. For the first push, I created a PAT, and used it for the password when running `git push`. In the past, this is the only time I have had to copy and past the PAT into git, and subsequent pushes are automatic without asking for a username or password. 

However, when I pushed my pagilaHW the second time, it again asked me for a username and password. Since the PATs disappear in Github, I had to generate a new token in Github and use it as a password. 

What am I missing here? Am I doing something wrong in Git?

**Comment by mikeizbicki** [comment]
The "right" workflow is to generate only a single PAT and save it to a file.  Then, whenever you need to use your password, you copy-paste the PAT from the file into the terminal.  For details on caching the credentials so that you don't have to do this copy-paste as often, see: https://stackoverflow.com/questions/5343068/is-there-a-way-to-cache-https-credentials-for-pushing-commits
