### ISSUE TITLE
Tests pass in Docker on lambda server but not on GitHub

### ISSUE THREAD

**Issue by anyu-yu** [mikeizbicki/cmc-csci143#137]
I'm having an issue where problem 11 for pagila-hw2 is passing on docker in my environment on the lambda server, but fails the auto test in docker on Github. I'm not sure why I'm having this error and I don't know how to debug it either. My current pushed code is in my repository, but I'm not sure if I should post it in this issue.

**Comment by mikeizbicki** [comment]
Most likely the problem is that you have nondeterministic sql queries caused by forgetting the `order by` clause.  Recall that without the `order by` clause, postgres is free to return the results in whatever order happen to be most convenient for it.  It just so happens that the convenient order on the lambda server is different than the one in github actions because the systems have different hardware specs, and so use different algorithms internally.  Adding an `order by` clause should fix the issue.

> My current pushed code is in my repository, but I'm not sure if I should post it in this issue.

It is always okay to post code here.  The goal for this space is to simulate the type of communication environment that you might have at a company/working on an open source project, where sharing code is encouraged.

**Comment by anyu-yu** [comment]
Thank you! Using ```ORDER BY "Actor Name"``` fixed it.
