### ISSUE TITLE
Output and Expected Seem to be the Same but Fail Test Case

### ISSUE THREAD

**Issue by DestrosCMC** [mikeizbicki/cmc-csci143#139]
My query for problem 3 on pagila3 returns the same values and order of countries but for some reason, there is a difference between expected and results. What could be the problem here?
```
$ diff expected/03.out results/03.out
89d88
<  Faroe Islands                         |         114.72
90a90
>  Faroe Islands                         |         114.72

```

**Comment by mikeizbicki** [comment]
There are two possibilities:

1. The lines are different in their whitespace.  In the past, this has happened to students who open the `expected/XX.out` file, modify it, and close the file using the `:wq` command instead of the `:q` command.  (Many students use `:wq` as their default "leave vim command", but this is a bad habit to be in.)  There are a number of ways to exactly see what the whitespace differences are, but there are a number of examples listed here: <https://superuser.com/questions/873420/difference-in-whitespace-between-two-files-on-linux>.
2. Also, noticing `89d88`, the line numbers in the two files are not the same.  This suggests to me that the line might be duplicated in one of the files but not the other.  Open vim and go to line 89 in both files to check.

**Comment by DestrosCMC** [comment]
The problem was that Liechtenstein had the same amount, so easy fix. Thank you!

**Comment by joeybodoia** [comment]
@DestrosCMC I'm running into the same issue with Faroe Islands and Liechtenstein. Based on the expected output, it appears that if two rows have the same "total_payments" value then alphabetical ordering should take precedence. However, I'm unsure on how to accomplish this, any advice?

**Comment by afroCoderHanane** [comment]
I litterally solved that by using the total_payments DESC, country ASC.
so 
```
ORDER BY total_payments DESC, country ASC;
```

**Comment by DestrosCMC** [comment]
@joeybodoia I added a second condition to order on:
```
ORDER BY total_payments DESC, co.country
```

**Comment by joeybodoia** [comment]
makes sense, thank you!
