### ISSUE TITLE
Port Forwarding

### ISSUE THREAD

**Issue by Asanchez2112** [mikeizbicki/cmc-csci143#15]
I am having issues port forwarding in Putty since I am using Windows. I believe I added the correct information to establish the ssh tunnel but when I try opening a connection, I get this error.
<img width="606" alt="Putty" src="https://user-images.githubusercontent.com/50669999/107166398-7df47a00-697b-11eb-9fbe-e73c6b818122.PNG">

**Comment by mikeizbicki** [comment]
A `connection timed out` error is going to be unrelated to port forwarding.  This means that you're not even able to connect to the lambda server at all.  My guess is that you forgot to add the port 5055 at the beginning putty settings screen.

More generally, however, I'm unfortunately not going to be very helpful with Windows/putty-specific problems, since I haven't touched a Windows computer in >10 years.  Hopefully, if you still can't get things working, another Windows-using student can chime in with some help.
