### ISSUE TITLE
denormalized query #2

### ISSUE THREAD

**Issue by erdsal4** [mikeizbicki/cmc-csci143#175]
I currently have the following query for question 2, but it still does a sequential scan on t2 because I wasn't able to replicate the 
`AND t2.tag LIKE '#%'` condition for the denormalized data. How would I do that?

```
SELECT 
tag,
count(*) as count
FROM (SELECT t1.data->>'id' as id, 
                jsonb_array_elements( COALESCE(t2.data->'entities'->'hashtags','[]') ||
                COALESCE(t2.data->'extended_tweet'->'entities'->'hashtags','[]'))->>'text' as tag 
FROM tweets_jsonb t1 
JOIN tweets_jsonb t2 on (t1.data->'id'=t2.data->'id') 
WHERE t1.data->'entities'->'hashtags' @@ '$[*].text== "coronavirus" '
OR    t1.data->'extended_tweet'->'entities'->'hashtags' @@ '$[*].text == "coronavirus" '
) t
group by (1)
ORDER BY count DESC, tag
LIMIT 1000;
```

**Comment by erdsal4** [comment]
Also, can we do one of the denormalized queries that include a "join"  together in class?

**Comment by leafsphere** [comment]
If you prepend a `'#'` to the beginning of the second column you're selecting in your subquery, it should be able to output what you need, i.e.:
```
'#' || (jsonb_array_elements(COALESCE(data->'entities'->'hashtags','[]') ||
        COALESCE(data->'extended_tweet'->'entities'->'hashtags','[]'))->>'text') AS tag
```
My denormalized query was able to work without doing any joins (in fact, none of my denormalized queries use joins!). The query would show all hashtags that have been used alongside `#coronavirus` in the same tweet due to the `WHERE` condition in your subquery. I'm not exactly sure why a sequential scan is still being done though, since mine performs bitmap index scans no matter whether I have the `'#' ||` portion or not, so that question might be related to the indexes that you've created so far.

**Comment by erdsal4** [comment]
@leafsphere That makes a lot of sense that we don't need to use joins since this is denormalized data, thank you very much!

**Comment by mikeizbicki** [comment]
It seems like @leafsphere's answer solved this (great answer btw!), so I won't add anything here.  But feel free to ask me more details in person.
