### ISSUE TITLE
Duplicate Key Value error when running index? 

### ISSUE THREAD

**Issue by katiewu71** [mikeizbicki/cmc-csci143#179]
When running a gin index, I get the following error: 
ERROR:  duplicate key value violates unique constraint "pg_class_relname_nsp_index"
DETAIL:  Key (relname, relnamespace)=(tweets_jsonb_expr_idx1, 2200) already exists.

Any leads on what the issue might be?

**Comment by mikeizbicki** [comment]
This line of your error message:
```
 ERROR: duplicate key value violates unique constraint "pg_class_relname_nsp_index"
```
indicates that you created a unique index using a command like
```
create unique index
```
rather than
```
create index
```
From a speed perspective, there is no difference between these two indexes.  But the former enforces the constraint that you cannot have duplicate entries.  The data happened to have a duplicate on your indexed column, and so that's why you were getting this error.

The fix is to remove the word `unique` from your index creation command.

PS.  In the future, you should surround all error messages in the triple backticks in order to create a code block and maintain proper formatting.
