### ISSUE TITLE
Anything Else in .gitignore

### ISSUE THREAD

**Issue by nguyenank** [mikeizbicki/cmc-csci143#18]
We went over extensively in class the importance of making sure `.env.prod.db`, where production credentials normally are, don't get into the git repo, and the tutorial for the lab/homework echoes that, but it also seems to suggest also putting `.env.prod` into `.gitignore`. Is that something we should be doing? In general, why would you want `.env.prod` not to be in version control? Is it just a preference thing like`.env.dev,` like you mentioned in class?

**Comment by mikeizbicki** [comment]
**Short answer:** As long as `.env.prod.db` is not in your repo, you won't have a grade penalty.

---

**Long answer:** It's just a preference about how many environment variables you want to store in the repo.  The only truely important thing is ensuring that the database password is not in version control.

Some people prefer hiding more environment variables than that because it makes it (potentially) even harder for an attacker to figure out how your system works and how they can break it.  For example, the `.env.prod` file contains information about how the servers are connected together on the network.  That knowledge could be useful to an attacker to help them with social engineering or knowing what services to exploit, and so some people might want to hide that information.  The cost is that it makes it harder for you to setup a new installation of your program from scratch because you have to re-specify all that information manually.

My personal philosophy is that I want my code to be as easy to setup as possible, and so I'll try to hide the minimum amount of information.  But that does bring a slight security risk that probably wouldn't be acceptable for a major product like Instagram.
