### ISSUE TITLE
Cannot connect to localhost

### ISSUE THREAD

**Issue by CurtisSalinger** [mikeizbicki/cmc-csci143#19]
I am working through the "dockerizing *" tutorial, and after making the necessary directories and doing `python manage.py run`, the server launches correctly and I see `running on http://127.0.0.1:5000/` but when I go to that in my browser, I am prompted with the error shown below. The only difference I can find is that I could not get `$python3.8 -m venv env` to run, so I tried `python3 -m venv env` which seemed to be successful but may be the cause of my problem, so I am unsure what to do from here.

Thanks for the help!

![Screen Shot 2021-02-11 at 5 10 30 PM](https://user-images.githubusercontent.com/38367847/107704958-0e88ce00-6c8c-11eb-99ad-7e1b026c568d.png)

**Comment by mikeizbicki** [comment]
**short answer:** you need to enable port forwarding, and connect through that port

**long answer:** The IP address `127.0.0.1` always refers to the current computer.  This is confusing because there are 3 different computers running (your laptop, the lambda server, and the docker container), and each one of those computers will refer to itself as `127.0.0.1`.

When you run flask on the container, the flask program will tell you it is running on `127.0.0.1`, but you cannot connect to it through that IP address, because that IP address means something different on your computer.  Instead, you need the `docker-compose.yml` file to connect port 5000 on the container to port `$UID` on the lambda server, and then you use port forwarding (`-L` in ssh or the putty option) to connect port 8080 on your laptop to port `$UID` on the lambda server.  Then, you will connect to `http://127.0.0.1:8080`, and that will be redirected through the lambda server to your container.
