### ISSUE TITLE
Can you provide solution to question 12 on Questions on Indexes and Access Algorithms

### ISSUE THREAD

**Issue by dustin-lind** [mikeizbicki/cmc-csci143#196]
Hi Mike, 

I would like to check my work on question 12 in Questions on Indexes and Access Algorithms because I'm not super confident in my answers. The question has 9 parts and it essentially asks how increasing the heap table by expanding the size of the tuples would influence the number of pages accessed by each of the different scan/aggregations/join algorithms that we've talked about in class. Below is how I answered them:

1. Sequential Scan -> Increase the number of pages accessed
3. Index Only Scan -> The number of pages accessed stays the same
4. Index Scan -> Increase the number of pages accessed
5. Bitmap Scan -> The number of pages accessed stays the same
6. GroupAggregate -> Increase the number of pages accessed
7. HashAggregate -> Increase the number of pages accessed
8. Nested Loop Join -> Increase the number of pages accessed
9. Hash Join -> Increase the number of pages accessed
10. Merge Join -> The number of pages accessed stays the same

Best,

Dustin

**Comment by mikeizbicki** [comment]
Seq scan and Index scan are correct.

For the index scan, there is not pre-sorting of the tuples, so we cannot group tuples in the same page together and access the same page only once, so we always access one page per tuple, occasionally accessing the same page multiple times if multiple tuples are in that page.  Spreading those tuples over more pages doesn't affect this.

For the bitmap scan, we pre-sort the tuples in order to group tuples in the same page together, so we will access each page exactly once.  The tuples will be spread out over more pages when the rows have more columns, and so we will need to access more pages.

For all of the Aggregate/Join methods, we are not directly accessing information in the heap pages (that comes from the scan method), so there is no change.  (Maybe slightly more accurate is that the change will depend on whatever scan method is used as input into the aggregate/join method.)
