### ISSUE TITLE
Initial docker-compose build error

### ISSUE THREAD

**Issue by jzlilili** [mikeizbicki/cmc-csci143#202]
Hello,
I'm trying to build docker-compose and getting the error 
```Could not find function xmlCheckVersion in library libxml2. Is libxml2 installed?```
But when I try to install `lxml`, I get the following message:
```Defaulting to user installation because normal site-packages is not writeable```
```Requirement already satisfied: lxml in /usr/local/lib/python3.6/dist-packages (4.6.2)```
so it seems like `lxml` is already installed, and trying to install `libxml2` only gives
```ERROR: Could not find a version that satisfies the requirement libxm12 (from versions: none)```
```ERROR: No matching distribution found for libxm```
Is there another package I have to install separately?

**Comment by ohorban** [comment]
I have the same problem

**Comment by mikeizbicki** [comment]
This problem is due to some dependencies being updated since I first announced the assignment.  Recloning should fix it.  See issue #184 for details.

PS.  Your message is very difficult to read due to incorrect markdown formatting.  In the future, please use code blocks (with triple backticks instead of inline code with single backticks) in order to post these types of messages.
