### ISSUE TITLE
Cannot delete contents of the databases in $HOME/bigdata folder via container

### ISSUE THREAD

**Issue by RuiluGao** [mikeizbicki/cmc-csci143#203]
Hi Mike, After I brought up the container, I ran this
```
docker-compose exec pg bash -c 'rm -rf $PGDATA'
```
to try to delete the contents in my bigdata folder and I encountered this issue
```
rm: cannot remove '/var/lib/postgresql/data': Device or resource busy
```
Any clue for this issue?

**Comment by mikeizbicki** [comment]
This is the expected result of running that command, and the contents of the `$PGDATA` folder should be empty at this point.

Postgres keeps the `$PGDATA` directory open at the operating system level, so the directory itself cannot be deleted.  But when postgres is not actively using the contents of that directory, it does not keep it open, and so the OS allows it to be deleted.  When you run the command you specified, it will first delete the contents of the directory (which succeeded), then try to delete the directory (which failed).

A variation of the command which won't perform the last, failing step is:
```
$ docker-compose exec pg bash -c 'rm -rf $PGDATA/*'
```
But otherwise the results of this command and yours should be the same.
