### ISSUE TITLE
Async state of the industry extra credit

### ISSUE THREAD

**Issue by mikeizbicki** [mikeizbicki/cmc-csci143#205]
There's a good presentation by spotify about how they use python async functions to improve their backend performance:

You can find the video at <https://www.youtube.com/watch?v=bckD_GK80oY&lc=Ugw9rZpVVSqT9WrCBEJ4AaABAg> and a writeup at <https://www.roguelynn.com/words/asyncio-we-did-it-wrong/>.

If you watch the video and reply to this issue with 3 things you learned, I'll give you 1 point of extra credit on your async/wardial assignment.

**Comment by edwardwu11** [comment]
Spotify:

- You can’t just throw out async and await key words to try to speed up your code. You have to figure out which blocks you can run asynchronously with which blocks you need to be sequential
- When performing shutdown processes and closing connections, try/enough/finally clauses are not sufficient. You should tell the loop how it should be deconstructed as soon as the program gets interrupted at a certain place. Once a program is shutdown, you should know what signals to respond to
- Make sure to set an exception handling either globally, individually, or a mix of both otherwise exceptions will go unnoticed or cause some weird behavior in your code.

**Comment by katiewu71** [comment]
* Some use-cases at Spotify for `asyncio` include a chaos monkey-like service for restarting instances in Google Cloud and an event-driven host name generation service for DNS. Although `asyncio` is pretty easy to use, it doesn’t automatically mean that you’re using it correctly. 
* Aside from the KeyboardInterrupt exception, your program should catch other common signals, too. If your service receives a POSIX signal, you probably want it to gracefully shut down. Some examples are `SIGHUP`, `SIGQUIT`, `SIGTERM`, and `SIGINT`.  
* We can use `pytest-asyncio` to test `asyncio` code, which is similar to testing non-asynchronous code. However, the `unittest.mock` and `pytest-mock` library don’t support asynchronous mocks, so coroutine functions need to be manually mocked.

**Comment by samcbogen** [comment]
1. You need to be really thorough with your loops (deconstruction, additional clauses, etc.) when you do closing connections. You need to be clear with the signals you need to respond to when you complete the shutdown processes. 

2. Async can be really easy to implement and use, but it does not guarantee your usage will be right! There was en example in the video regarding Spotify's usage of asyncio, and they needed to utilize Google Cloud and restart several instances to make it work.

3. When you are trying to make your code faster, you cannot just use the key words that you want to speed it up. You are going to need to figure out the code blocks that you want asyncio to be used on, and the remainder of the blocks that you do not want to use asyncio on.

**Comment by leafsphere** [comment]
* Using `await queue.put(msg)` instead of `asyncio.create_task(queue.put(msg)` will block the lines that come after within the coroutine, which would be an issue if the size of the queue were limited, or if you were waiting for space to be freed up.
* If you don't acknowledge a message with a predefined time frame, it will often get redelivered, so it's good to complete the `save` and `restart_host` tasks before the message is cleared up. You could use sequential `await`s, but another method would be using `callback`s on a completed task: wrapping both tasks using `asyncio.gather()`, attaching a `callback` to the created object, and then `await`ing it. But if you want the cleanup to be non-blocking, you could first `await` the `asyncio.gather()` object before `await`ing the cleanup.
* It's possible for an error to arise outside of your `except` clause, which can cause the service to end up in an incomplete or otherwise unknown state. One possible resolution would be adding the signal handlers you want to respond to after the loop, which eliminates the need for that explicit catch clause.

**Comment by alex-muehleisen** [comment]
1. Developers have as much control as they need in `asyncio`, due to the module's several layers of abstraction. It's simple for "hello-world" tutorials and such, but a lot more complicated when implementing real-world solutions.

2. The system needs to be shut down 'gracefully', if it receives a signal of some sort. This entails cleaning up database connections, stopping message consumption, and not accepting any new requests. The signals we need to react to are: nginx, Apache, uWSGI, Gunicorn, and Docker. There is no standard and this can get quite messy with conflicting signals. 

3. `asyncio` has a built-in debugging mode, which can be turned on by running relevant scripts. For anything not handled by this mode, the `print_stack()` method can be used to debug manually. This displays the stack for every running task.

**Comment by cristywei** [comment]
- If you use `except KeyboardInterrupt`, the signal could happen outside of the exception, so attaching a signal handler to the loop is a good practice to avoid the service ending up in an incomplete or unknown state. Handling how to react to certain signals can vary and is dependent on what you want to do.
- Setting `return_exceptions=True` is important because it prevents the exceptions from being handled by the default handler; when there is no default handler specified, exceptions will get swallowed up.
- Debug mode can highlight slow to finish tasks and potentially any unnecessary and slow blocking tasks; by default "slow" is > 100ms, but this can be adjusted with `slow_callback_duration`.
