### ISSUE TITLE
Issue with Search Engine

### ISSUE THREAD

**Issue by afroCoderHanane** [mikeizbicki/cmc-csci143#209]
Hey @mikeizbicki 
I was having an issue of disk quota error and decided to reclone your repo.
I was able to build the docker but now  I am facing :

```
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) ERROR:  pgbouncer cannot connect to server

(Background on this error at: https://sqlalche.me/e/14/e3q8)
```
When I run `docker-compose logs` I am facing this 
`password authentication failed for user "novichenko"`. Is there anything wrong with your create_password file ??

**Comment by mikeizbicki** [comment]
I do not believe there are any problems with the `create_password.sh` file.  Sorry, I'm not sure how to offer advice here, and we'll probably need to take a look in person.

**Comment by leafsphere** [comment]
For anyone else who may be running into the problem, the solution we found during office hours was:

1. editing the `docker-compose.yml` file to rename the volume location so that a fresh volume will be created with the most recent `.env.prod` credentials, i.e. from
```
volumes: 
    - $HOME/bigdata/search_engine:/var/lib/postgresql/data
```
to
```
volumes:
    - $HOME/bigdata/search_engine2:/var/lib/postgresql/data
```

2. in `services/downloader_warc/Dockerfile`, deleting lines 44-46, which are:
```
$ RUN pip3 --version
$ RUN pip3 install pip --upgrade
$ RUN pip3 --version
```
Removing these lines will help speed up the WARC downloading process so that the first 80 lines of the `downloader_warc` `Dockerfile` match those of the `pg` `Dockerfile`.
