### ISSUE TITLE
Failed to open page

### ISSUE THREAD

**Issue by CurtisSalinger** [mikeizbicki/cmc-csci143#21]
After updating my Dockerfile to install netcat, I am trying to rebuild and run to test that it has al and I keep seeing the error below (first is in my terminal, and second is on my browser. I thought it was an issue with my ports, but I have confirmed those are all correct, so I'd love some guidance here. Thanks!

<img width="700" alt="Screen Shot 2021-02-12 at 4 02 40 PM" src="https://user-images.githubusercontent.com/38367847/107822226-bdd8aa00-6d4b-11eb-8097-66f7cf3df6b4.png">

<img width="301" alt="Screen Shot 2021-02-12 at 3 56 18 PM" src="https://user-images.githubusercontent.com/38367847/107821660-db594400-6d4a-11eb-9526-86d997d2beb6.png">

**Comment by mikeizbicki** [comment]
The messages in your terminal are caused because ssh is forwarding your browser request to the appropriate port on the lambda server, but there is nothing listening on the lambda server at that port.  Every connection through port forwarding that doesn't get a response generates one of those lines.  (Safari is making 3 attempts to connect.)

One of the following is the underlying cause.  Either:

1. You don't a flask container running.  (Use `docker ps` to check this.)  In this case, you need to start the container with `docker-compose up`.  It's possible that when you modified the Dockerfile you made a mistake that is causing the server not to start.

1. If you're sure that the container is running, then your port settings are incorrect in the `docker-compose.yml` file.

**Comment by amytam01** [comment]
I have a similar error, so I checked for underlying causes as Mike suggested. However, my flask container is running, and my port settings seem correct. I've attached a screenshot of each below: 

Terminal error:
![Screen Shot 2021-02-12 at 2 46 13 PM](https://user-images.githubusercontent.com/38165346/107830698-47cf4580-6d41-11eb-98e0-57e7f48ee084.png)

Flask contianer running (with `docker ps`):
![Screen Shot 2021-02-12 at 2 48 15 PM](https://user-images.githubusercontent.com/38165346/107830736-59b0e880-6d41-11eb-923b-86dcebe7d651.png)

`docker-compose.yml` file:
![Screen Shot 2021-02-12 at 2 48 53 PM](https://user-images.githubusercontent.com/38165346/107830785-6f261280-6d41-11eb-9148-9d95be83efb1.png)

Please let me know your thoughts. Thanks!

**Comment by mikeizbicki** [comment]
@amytam01 You do not have a flask container running.  Notice that the `docker-compose.yml` file lists two services: `web` and `db`, but running `docker ps` lists only a single container `flask-on-docker_db_1`.  This likely means that there was an error in you `web` container that caused it to shutdown.

You can use the command
```
$ docker-compose logs web
```
to see the logs from your `web` container and diagnose what is causing the container to shutdown.  Alternatively, you can view the logs by not including the `-d` flag in `docker-compose up`.
