### ISSUE TITLE
Final Grades in Sakai

### ISSUE THREAD

**Issue by mikeizbicki** [mikeizbicki/cmc-csci143#224]
I will be entering grades into the portal tomorrow afternoon.  I've graded all of your homeworks (and everyone completed the caveat tasks), so whatever is in sakai is what I will be entering.  You should all make sure that there are no errors.

There are a handful of people who are just a few points away from a letter grade change, so I'm offering one final extra credit worth up to three points to help you all out.  You can select up to 3 videos from [pycon 2021](https://www.youtube.com/playlist?list=PL2Uw4_HvXqvYk1Y5P8kryoyd83L_0Uk5K), watch them, and email me 3 things you learned from each.  For each video, I'll give you one more point in sakai.  The deadline for this is tomorrow (Friday 13 May) at noon, since I'll be entering grades right after that.

I hope you all have a great summer :)

**Comment by Luew2** [comment]
Hey Mike!

I wanted to ask, do i have an 86 (B) or an 87 (B+)? In total I've lost 64
points, but I didn't account for the caveat task and the extra credit point
I received. If each caveat task counts as 1 extra credit point I have
409/470 total, otherwise I have 407/470.


Let me know! If I'm at 407 I'll watch some videos :)

- Lucas
