### ISSUE TITLE
Permission Denied and Operation not Permitted 

### ISSUE THREAD

**Issue by Aser-Abdelfatah** [mikeizbicki/cmc-csci143#248]
I'm trying to unzip the file geoTwitter20-02-15.zip using `data/Twitter\ dataset/geoTwitter20-02-15.zip unzip -p command`, but it gives me an error "permission denied". When I tried to use the command chmod u+x followed by the full path to give myself permission, I receive the error Operation not Permitted.

**Comment by mikeizbicki** [comment]
I'm sorry, but I don't understand your question.  I think that's partially due to the weird formatting you've used (inline code instead of code blocks) and partly because you're missing some information.  If you reask it, then I'll try to answer.

**Comment by Aser-Abdelfatah** [comment]
Sorry for the weird formatting.
I'm trying to do the second part of the lab where we should count the number of times the word "coronavirus" was mentioned in the tweets published on 20-02-15. My assumption is I should unzip geoTwitter20-02-15.zip as the first step. My code for that is
 ```
data/Twitter\ dataset/geoTwitter20-02-15.zip unzip -p
  ```
However, I receive the error permission denied. I tried to give myself a permission using the command 
```
chmod u+x  data/Twitter\ dataset/geoTwitter20-02-15.zip
```
However, I receive the error operation not permitted. Is this the right command to give myself permission?

**Comment by mikeizbicki** [comment]
I'm assuming you mean the following: (I've added the `$` out front to indicate that this is being typed directly into the shell)
```
$ data/Twitter\ dataset/geoTwitter20-02-15.zip unzip -p
```
I believe you are trying to use the `unzip` command, but you are not typing it first after the prompt.  Instead, you are typing the zip file.  The shell is interpreting this as you are trying to run the zip file, which you don't have permission to do (because no one has permission to do because it's not executable), and giving you the corresponding error.
