### ISSUE TITLE
f-string missing placeholders

### ISSUE THREAD

**Issue by cschulz21** [mikeizbicki/cmc-csci143#25]
when running 
`docker-compose -f docker-compose.prod.yml up -d --build`
I ran into the following error.

```
./project/__init__.py:52:12: F541 f-string is missing placeholders
The command '/bin/sh -c flake8 --ignore=E501,F401 .' returned a non-zero code: 1
ERROR: Service 'web' failed to build
```

This appears to be coming from `__init__.py` line 52

```
 46 @app.route("/upload", methods=["GET", "POST"])
 47 def upload_file():
 48     if request.method == "POST":
 49         file = request.files["file"]
 50         filename = secure_filename(file.filename)
 51         file.save(os.path.join(app.config["MEDIA_FOLDER"], filename))
 52     return f"""
 53     <!doctype html>
 54     <title>upload new File</title>
 55     <form action="" method=post enctype=multipart/form-data>
 56       <p><input type=file name=file><input type=submit value=Upload>
 57     </form>
 58     """
```
I tried commenting out this code from the file and and the command above ran without problem. Any suggestions?

**Comment by CurtisSalinger** [comment]
Hey! I think you need to tab in lines 53-57 to comply with Flake8's linting check. Hope this helps! At least thats what I understand from this documentation about fstrings. https://realpython.com/python-f-strings/

**Comment by cschulz21** [comment]
Thanks for the advice. Unfortunately, after adding the spacing I am still running into the same problem. My guess is this is due to no variables in the f string in "placeholders" ` {  } ` but I am new to f strings so I could be very wrong. When I comment out the line 
```
RUN flake8 --ignore=E501,F401 .
```
in `services/web/Dockerfile.prod` I am able to reach the upload page. I can select a file and click upload although when I upload I  get an internal service error. (not sure if this is a different problem altogether)

**Comment by mikeizbicki** [comment]
@cschulz21 You're right that the error is due to using the f-string without placeholders.  The solution of not running flake8 is fine for this assignment.  It would also be possible to delete the `f` character on the line
```
 52     return f"""
```
or to change the flake8 command to
```
RUN flake8 --ignore=E501,F401,F541 .
```
which instructs flake8 to ignore this particular "problem".

My guess about why this happened is that it's another dependency updating issue.  Notice that on the lines
```
RUN pip install --upgrade pip
RUN pip install flake8
```
the specific version of flake8 is not specified.  Therefore, pip will install the latest one.  In this case, the latest flake8 has more checks than older versions did, and these new checks are causing a previously passing program to fail.

The meta-lesson is to always specify exact dependencies on any code that you're writing.
