### ISSUE TITLE
Question on Creating Users Table

### ISSUE THREAD

**Issue by sophiahuangg** [mikeizbicki/cmc-csci143#269]
Hi Mike,

When I try to rebuild the images and rerun the containers for the SQL portion, I keep getting this error:

<img width="678" alt="Screen Shot 2023-02-11 at 10 45 17 AM" src="https://user-images.githubusercontent.com/89934020/218275599-02f8191b-276c-4849-8eb0-f1bf25dc601b.png">

I think my Users table was created since I'm able to see this:

<img width="762" alt="Screen Shot 2023-02-11 at 10 41 46 AM" src="https://user-images.githubusercontent.com/89934020/218275486-3607ef18-b472-42a1-b02e-80bfbb674105.png">

so am a little stuck on where the error is arising from. I was wondering if you have any suggestions on how to go about this error:

`AttributeError: module 'sqlalchemy' has no attribute '__all__'. Did you mean: '__file__'?` I tried upgrading the package, but it didn't seem to do anything.

**Comment by mikeizbicki** [comment]
If the future, you should include code blocks and not screenshots.  Google cannot index screenshots of text, and so people are very unwilling to provide help based on screenshots because then no one else will be able to find the answers in the future.

The `AttributeError` indicates that this is likely somehow a version problem with sqlalchemy, and that fixing versions will likely solve the problem.  You mention upgrading your version, but upgrading is rarely the solution to docker problems.  At some point in time, this was working in the past, and so you need to go backwards in time by downgrading version numbers.  That said, I don't believe I had to modify any version numbers to get things working.

**Comment by emjuliet** [comment]
I also got this same error. I uninstalled and installed the versions used in the tutorial but it is still not working.
