### ISSUE TITLE
Docker Volumes

### ISSUE THREAD

**Issue by chenpatrickc** [mikeizbicki/cmc-csci143#28]
In the development server when I upload an image or create a `.txt` file in the docker container, that same file **does** appear in the lambda server folder.

- I understand that this behavior is due to `volumes` in the `docker-compose.yml`  file.

However, in the production server when I upload an image or create a `.txt` file in the docker container, that same file **does not** appear in the lambda server folder. I ran into this when trying to access images I uploaded while running the production server, after switching back to the development server.

- I see that the syntax is different in setting `volumes` in the `docker-compose.prod.yml` file. Is there a reason we do not want the same behavior as in the development server?

**Comment by mikeizbicki** [comment]
> Is there a reason we do not want the same behavior as in the development server?

Great question.  In general, there is no rule about which types of volumes are better for dev/prod environments.  It always depends on the developers preferences.  In this tutorial, they did them differently just to illustrate the difference, and not because it's necessarily the "right" thing to do.
