### ISSUE TITLE
Question About SCP

### ISSUE THREAD

**Issue by sophiahuangg** [mikeizbicki/cmc-csci143#300]
Hi Mike! I have a question about the `scp` command. I'm trying to move something onto my Lambda Server, but I am having a lot of trouble with it. This is the command I'm running:

`scp -p 5055 (putting direct path to file name here) Sophia.Huang.24@(IP Address):/home/Sophia.Huang.24/twitter_coronavirus`

This is the error I get:
`ssh: connect to host (Address) port 22: Operation timed out lost connection` 

I was wondering if you had any suggestions?

**Comment by mikeizbicki** [comment]
Preface: The command and error you report should be in code blocks and not inline code, since they are a complete line and not a partial line.

Answer: The `scp` and `ssh` commands have an inconsistent interface for specifying the port number.  In `ssh` it is `-p`, but it `scp` it is `-P` with a capital P.  Fixing that should fix the problem.

**Comment by sophiahuangg** [comment]
Got it, thank you!
