### ISSUE TITLE
twitter hw/general issue

### ISSUE THREAD

**Issue by afzal-p** [mikeizbicki/cmc-csci143#31]
I have started to run map.py on all of the .zip files using nohup. 
It seems to have worked when I first checked the running processes using 'ps'.
However, now when I login or try to use any command I am constantly receiving the message: 

`-bash: fork: retry: Resource temporarily unavailable`

**Comment by amytam01** [comment]
I have the same issue. I accidentally didn't add a block of code in my map.py file so I was rerunning` nohup` as to make up for the files that weren't added due to this missing block of code (I have .lang zip files but no .country zip files). I was suggested to kill processes as to fix my forking issue but the message wouldn't allow me to do so.

Edit: The issue seems to have gone away but now I'm concerned I have a bunch of forks

**Comment by mikeizbicki** [comment]
**short answer:** @Afzal-Patel and @amytam01, I've killed some of your processes, so you should be able to log in now.

**long answer:**

On the lambda server, you have a limit that you're only allowed to have 512 running processes.  Every time you login with ssh it must create two new processes (one for ssh, and one for the bash terminal), plus every command you run on the shell is another new process.  These processes are all created by running the `fork` syscall, and the fact that you had exceeded your allowed number of processes is why you were getting these error messages.  The purpose of this limit is to ensure that one user doesn't accidentally degrade performance for other users.

I was able to complete all the assignments with the 512 process limit, but I did not try doing the twitter assignment while having docker containers running.  My guess is that with both of those together, you are exceeding the limits.  You can try shutting down docker to free up processes for twitter, or you can try running your twitter code in smaller batches (i.e. running on only 1 month at a time, creating 30 new processes, rather than running on the whole year at once, creating 365 new processes).
