### ISSUE TITLE
Question on Quiz Grading

### ISSUE THREAD

**Issue by sophiahuangg** [mikeizbicki/cmc-csci143#324]
Hi Mike!

I know this is kind of a big ask, but I was wondering if there was any chance you would be open to letting us gain points back on quizzes? For example, dropping our lowest quiz grade/having an opportunity to boost our quizzes somehow? Thank you!

**Comment by KaranGoel1** [comment]
+1

**Comment by jaymaliye** [comment]
+1

**Comment by laurenleadbetter** [comment]
+1

**Comment by Aser-Abdelfatah** [comment]
+1

**Comment by livrenfro** [comment]
+1

**Comment by mariagerges** [comment]
+1

**Comment by mikeizbicki** [comment]
Yes.  In general, my grading philosophy is that your grade should reflect your knowledge of the subject, and not how well you happened to perform on an individual day.  So in order to get points back, you will somehow have to demonstrate that you have mastered the harder concepts in this class.

The only concrete idea I have for this is the game mentioned in #319.  Completing that game reflects mastery of the concepts of locks, and so that's why you get extra credit.  If you propose similar tasks that would demonstrate mastery of other concepts, I'd be happy to award them extra credit.
