### ISSUE TITLE
Lambda Server being incredibly slow

### ISSUE THREAD

**Issue by ifreer23** [mikeizbicki/cmc-csci143#326]
Is anyone else's Lambda Server taking a while to log into? And once I've logged in I can barely type commands without it freezing? Just wondering if it's my computer or the server

**Comment by sybf-pro** [comment]
+1

**Comment by BITEEE0308** [comment]
+1

**Comment by sophiahuangg** [comment]
+1

**Comment by kushpetal** [comment]
+1

**Comment by tennisoctocat** [comment]
+1
@mikeizbicki could we all have an extension for this homework assignment (perhaps until Friday or next Tuesday) given the unexpected slowdown of the lambda server? It seems that it's affecting everyone and that even simple tasks like spinning up the containers are taking >10 min. In addition, since this is our last homework assignment, it won't cause us to be behind schedule at all. Thanks!

**Comment by snarayan23** [comment]
+1

**Comment by mariagerges** [comment]
+1

**Comment by samujala** [comment]
+1

**Comment by jaymaliye** [comment]
1+
