### ISSUE TITLE
Issue running docker-compose exec pg_normalized_batch bash -c 'rm -rf $PGDATA'

### ISSUE THREAD

**Issue by nickwilson3** [mikeizbicki/cmc-csci143#338]
When I run the command:
```
docker-compose exec pg_normalized_batch bash -c 'rm -rf $PGDATA'
```
I receive this error:
```
/home/Nicholas.Wilson.23/.local/lib/python3.6/site-packages/paramiko/transport.py:32: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography. The next release of cryptography (40.0) will be the last to support Python 3.6.
  from cryptography.hazmat.backends import default_backend
```
Also, after running
```
docker-compose up -d --build
```
successfully, should the containers be showing up in 
```
docker volume ls
```
immediately? Any advice?

**Comment by tennisoctocat** [comment]
I've been getting the `CryptographyDeprecationWarning` as well but I don't think it's a big deal since it hasn't prevented any of my code from working (it seems to just be a warning as opposed to an error). 

I'm not sure about the `docker volume ls` command. But if `docker-compose up -d --build` finishes successfully and there's an issue with your docker volumes or containers you might be able to see what went wrong by running `docker-compose logs`.
