### ISSUE TITLE
schema-indexes.sql not running

### ISSUE THREAD

**Issue by nickwilson3** [mikeizbicki/cmc-csci143#346]
After adding the indexes to services/pg_normalized_batch/schema-indexes.sql, I run the:
```
$ time docker-compose exec pg_normalized_batch   ./check_answers.sh sql.normalized_batch
```
command, but I still get the same run times that I did before adding the indexes. Any advice?

**Comment by hfmandell** [comment]
You need to actually create them in your `psql` environment. Writing them in the `schema-indexes.sql` file doesn't do anything, it might just be for grading purposes.

After you run your `CREATE INDEX ON ...` commands in `psql`, you can check that they exist by running `\d [INSERT TABLE NAME]`. The indexes should show up if they've been created correctly. Beware, creating these indexes can take anywhere from 5-40 minutes each.

**Comment by tennisoctocat** [comment]
You can also make it so that the indexes will be created when you initialize your database. To do so, you can add this line to your Dockerfile:
```
COPY schema-indexes.sql /docker-entrypoint-initdb.d/02.sql
```
Note that everything in `docker-entrypoint-initdb.d` is only run when initializing the database, so if you already have a database up and running, adding this line might not result in your indexes being created. So if this is the case @hfmandell's answer is probably the way to go.

**Comment by nickwilson3** [comment]
Thank you for the help! I was able to create the indexes in psql and then when I checked the answers and run time, I was able to get under 4 seconds for the pg_normalized_batch database, but got 5.5 seconds for pg_denormalized. I then stopped working for the night and just logged back into terminal and had to build the container again, load the load_tweets_parallel. sh file, and create the indexes again, but when I test the denormalized database, it is not running the indexes even though the indexes show up in psql when I run \d [table name]. Did anyone else run into this problem?
