### ISSUE TITLE
Git Push Issue

### ISSUE THREAD

**Issue by gibsonfriedman** [mikeizbicki/cmc-csci143#374]
Hi @mikeizbicki.
When I try to push the homework using "git push origin master" I'm prompted to enter my username and password and when I do I get this error message:

remote: Support for password authentication was removed on August 13, 2021.
remote: Please see https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currently recommended modes of authentication.
fatal: Authentication failed for 'https://github.com/gibsonfriedman/continuous-integration.git/'

Is there something I should do to clone my repo differently?

**Comment by henrylong612** [comment]
Hi @gibsonfriedman,

If I remember correctly, you have to enter the GitHub [personal access token (PAT)](https://docs.github.com/en/enterprise-server@3.4/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token) that you created rather than your GitHub password.

Let me know if that works!

**Comment by gibsonfriedman** [comment]
That worked thanks @henrylong612!
