### ISSUE TITLE
Lambda server not working - disk quota exceeded

### ISSUE THREAD

**Issue by oliver-ricken** [mikeizbicki/cmc-csci143#393]
I'm having some issues with the lambda server. I tried to log in on my usual terminal, Warp, but the message `starting shell` would not go away, and the shell session didn't start. 

I then tried using the base Mac terminal, and I was able to access the shell. However, when I try and run any command, such as a `cd` into a new directory, I see the following error message:

```
-bash: cannot create temp file for here-document: Disk quota exceeded
```

Not sure if this is an issue on my end or with the server. I tried running `df` and it does not look like the server is under much load. I then tried removing some of the `map.geoTwitter20-01-01.zip.dat` files in my `lab-posix-mapreduce` directory to free up some space, but I keep getting the same error message as above, and I'm not able to delete any files.

Any help would be appreciated! I wasn't having any issues with the server yesterday, and this is the first time logging in since, so this seems weird! Thanks :)

**Comment by sjanefullerton** [comment]
Hi, I am running into the same issue. I wasn't having this issue with the server yesterday either.

**Comment by irajmoradi** [comment]
If you hit an issue with the disk quota I would recommend running 

```du -sh```
in your main directory.
If it is gigabytes high that means you have to delete or move some files. If you still have the llama 7b file in that directory, or in a folder not named bigdata, you should move it into the bigdata folder, or maybe delete it since it was only needed for the first lab and you can just redownload it. 

While you hit a diskquota you can usually still run commands, just not write any files or use tab complete. Thus you should be able to delete files.

**Comment by oliver-ricken** [comment]
Hi all, @irajmoradi kindly provided me with some help, and his suggestion seems to have worked. From what I understand, I was maxing out my storage quota on my end of the server. I was able to check this with the following command:

```
du -sh
```

For me, the file that was causing the issue was the llama 7b file from the goodreads lab. First, I `cd` into my home directory, and then ran the following command:

```
mv mistral-7b-instruct-v0.2.Q5_K_M.llamafile bigdata/
```

as the big data folder has a larger storage quota. Now when I run `du -sh`, I see that I have enough space.

Thanks @irajmoradi!
