### ISSUE TITLE
UNIX Process review: Kill a nohup question

### ISSUE THREAD

**Issue by CurtisSalinger** [mikeizbicki/cmc-csci143#4]
Hey everyone!
I was going through and doing the unix processes review, and I am having trouble killing my `./script.sh` process after I ran it with the `nohup` command.

I have verified that it is running in the background by checking it with `wc -l output2` and seeing that the number is increasing, but when I run `ps -ef | grep Curtis.Salinger.22`, I only see three processes as shown below in the image. When I kill the first it says not permitted, when I kill the second it says No such process, and when I kill the third it logs me out of the lambda server. So I am not sure how to find the **PID** of `./script.sh` process to kill it. 

Thanks for the guidance here!

<img width="720" alt="Screen Shot 2021-01-26 at 1 28 46 PM" src="https://user-images.githubusercontent.com/38367847/105889498-3addf280-5fdc-11eb-87ac-a5cb1b3e67f8.png">

**Comment by mikeizbicki** [comment]
The problem is that the output of the `ps -ef` command is truncating your username since it is particularly long.  You can see in the first column that there is 1 `root` user and 2 `Curtis.+` users.

If you change your grep command so that the pattern it is searching for is `'Curtis\.\+'`, this should fix the issue.  Note that the `.` and `+` characters have special meaning in grep as a regular expression, so you need to either escape them with `\.` and `\+` or exclude them entirely (i.e. search for `Curtis`).

**Comment by whosayn** [comment]
If you're still having trouble, the below command should allow you to find the **PID** of the process, since it'll be the one writing to the output2 file.
```
lsof | grep output2
```
you can then use the **PID** kill it.
