### ISSUE TITLE
Pagila HW 3  - Pass Tests On Lambda Server But Not GitHub

### ISSUE THREAD

**Issue by nguyenank** [mikeizbicki/cmc-csci143#40]
I'm having an issue where when I run `check_answers.sh` on the lambda server, all the tests pass, but when I push to GitHub the tests workflow fails. When I check the workflow results, it appears like everything is running properly, but when `check_answers.sh` is running in the workflow, the test for just `sql/04.sql` fails, and I have no idea why this would be the case.

**Comment by mikeizbicki** [comment]
This is almost certainly due to an incorrect `order by` clause.  Recall that without `order by`, the results are non-deterministic (i.e. postgresql gets to determine the results however it wants).  My guess is that your postgres on the lambda server just happens to be choosing a "nice" ordering that matches what the results are supposed to be, but the postgres on the lambda server has different environmental conditions and so is choosing a different ordering.

**Comment by nguyenank** [comment]
Yeah that was it! I had gotten dinged right at the end in other problems for not having an ORDER BY, so I assumed I got them all then, but clearly not. Thanks!
