### ISSUE TITLE
Twitter HW Permission Denied Error

### ISSUE THREAD

**Issue by westondcrewe** [mikeizbicki/cmc-csci143#402]
Has anyone else encountered a "Permission Denied" error when trying to run the very first 
```./src/map.py --input_path=/data/Twitter\ dataset/geoTwitter20-02-16.zip``` 
command of the Twitter HW1?

**Comment by KentaWood** [comment]
I went to QCL and the mentor checked the permission I had on the map.py by doing `$ls -l src`. And long story short it you'll see the three files like this 
```
-rw-rw-r--+ 1 anwa2021 students 1963 Jan 30 17:56 map.py 
-rw-rw-r--+ 1 anwa2021 students  612 Jan 30 17:56 reduce.py
-rw-rw-r--+ 1 anwa2021 students  722 Jan 30 17:56 visualize.py
```
meaning that we only had read and write permissions on the files, hence why running the python code on the file didn't work as we don't have the permission for it 

so then you want to run a command so that adds the permission to execute the files 
```
chmod +x src/map.py src/reduce.py src/visualize.py
```

so that now you have permissions to execute code on the file and can be seen by the added x to the list 

```

-rwxrwxr-x+ 1 anwa2021 students 1963 Jan 30 17:56 map.py
-rwxrwxr-x+ 1 anwa2021 students  612 Jan 30 17:56 reduce.py
-rwxrwxr-x+ 1 anwa2021 students  722 Jan 30 17:56 visualize.py

```

**Comment by mikeizbicki** [comment]
@KentaWood Great answer.  I've awarded +1 extra credit to you in sakai for the response.

(I don't always award extra credit for responding to github issues, but I occasionally do for particularly good contributions to the class.)
