### ISSUE TITLE
Lab Issues

### ISSUE THREAD

**Issue by baron-zeng** [mikeizbicki/cmc-csci143#407]
Hi Mike,

Both my partner and I have established port forwarding using the code below (replacing the username with our own and 5000 with the other person's $UID).

```
ssh <username>@lambda.compute.cmc.edu -p 5055 -L localhost:8080:10.253.1.15:5000
```

I followed the steps and created the index.html file and server.sh file. After I start the server with:

```
$ chmod u+x server.sh
$ ./server.sh
```

My partner has tried multiple methods of connecting to my we server including:

1. connecting to my server via shell (replacing <partner_uid> with my own, and then pasting the URL http://localhost:8080/ into firefox

```
netcat localhost <partner_uid>
```

2. directly pasting the URL http://localhost:8080/ into firefox

3. The previous two steps with the URL http://10.253.1.15:5000/ (replacing 5000 with my $UID)

However, in all cases he gets the following output:

```
channel 3: open failed: connect failed: Connection refused
```

Do you know what the issue might be?

Thank you,
Baron

**Comment by mikeizbicki** [comment]
This is a good question (and well asked).  Your correct to be thinking that the problem is related to the ports and addresses.  Unfortunately, the problem is subtle enough that I'm not going to able to explain an answer over github in a way that makes sense, and we'll have to address this in person during office hours if you're still having problems.
