### ISSUE TITLE
docker-compose Permission denied

### ISSUE THREAD

**Issue by henrylong612** [mikeizbicki/cmc-csci143#425]
When I run the command below, I get the following output:
```
$ docker-compose build
-bash: /usr/bin/docker-compose: Permission denied
```
Is anyone else getting this? Why might this be?

**Comment by mikeizbicki** [comment]
The error message shows that you are trying to run the `docker-compose` that is located system-wide at `/usr/bin/docker-compose` instead of the one installed locally in your home folder at `$HOME/.local/bin/docker-compose`.  (The later location is where `pip install` places programs.)

The most likely cause is that you haven't run `pip3 install docker-compose`.  If you have done that and it's still not working, then the next most likely fix is re-logging into the lambda server.

**Comment by rachelHoman** [comment]
I had the same issue and re-logging into the lambda server fixed it!

**Comment by henrylong612** [comment]
Thanks @mikeizbicki and @rachelHoman !

**Comment by giffiecode** [comment]
I run the `pip3 install docker-compose` but got this error 


`Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-7gswn9ym/bcrypt/ `

**Comment by rajabatra** [comment]
When I run `pip3 install docker-compose`, I also get the error 
`Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-buov5y7l/cryptography/`
