### ISSUE TITLE
docker-compose won't install in .local

### ISSUE THREAD

**Issue by JTan242** [mikeizbicki/cmc-csci143#427]
When I upgrade pip I get this

```
jetanb@lambda-server:~$ which pip3
/usr/bin/pip3
jetanb@lambda-server:~$ pip3 install pip --upgrade
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pip in ./.local/lib/python3.6/site-packages (21.3.1)
jetanb@lambda-server:~$ which pip3
/usr/bin/pip3
```
Then when I try to install docker-compose and type $which docker-compose, I get no output

This is a fresh account so I had just installed docker. Is there anything else I could be missing?

**Comment by mikeizbicki** [comment]
`pip3` installs python executables into the `./local/bin` folder.  This needs to be in your path in order to run the updated pip you've tried to install, but it is not by default in the path.  [The instructions here for configuring the lambda server account](https://github.com/mikeizbicki/cmc-csci046/blob/2023spring/topic_00_unix/lambda-server.md) add `.local/bin` to the path (in addition to many other things).  I recommend running those commands on your new account to get "sane" settings again.
