### ISSUE TITLE
Lagging lambda server

### ISSUE THREAD

**Issue by gPlacide** [mikeizbicki/cmc-csci143#46]
Anyone else experiencing an immense lagging on the server? Or it's just from my end?

**Comment by amytam01** [comment]
Yep! Me too. I'm expecting that it's temporary though

**Comment by mikeizbicki** [comment]
Students in my other class have just started a computationally heavy assignment, and so that's likely the cause of the slowness.

Fortunately, there's a way for you to tell the lambda server that your programs should get priority over there's.  On linux, the priority of a program is determined by its "niceness level".  Nicer programs always defer to less nice programs and let the less nice programs run first.  By default, everyone's programs are run at the maximum niceness level of 19.  You can modify the niceness level of your programs down to a niceness of 5, and this is especially useful for running programs like vim that require realtime interaction.  To run vim with the modified niceness level, use the command
```
$ nice -n -14 vim
```
The `-14` comes from the fact that 19-14=5.  5 is the minimum niceness level that you are allowed to use, and you'll get error messages if you choose something smaller.

To check the niceness levels of running processes, use the command
```
$ ps -o "%p %y %x %c %n"
```
You can reference https://www.tecmint.com/set-linux-process-priority-using-nice-and-renice-commands/ for more details.
