### ISSUE TITLE
Question Regarding Final 

### ISSUE THREAD

**Issue by luisgomez214** [mikeizbicki/cmc-csci143#515]
Hello Mike,

I had a few questions that I didn’t get to ask after class yesterday. For the final exam, I know you mentioned that it would be 

One without a JOIN
One with a JOIN (possibly more than 1 table)
One with a full text search (possibly with a JOIN)

but the questions we have been practicing during class are over creating indexes. Will the final be over writing SQL queries or like the questions in the practice final pdf on github? I noticed that the practice problems do not have JOIN commands.  Other than reading the articles, how else do you recommend studying for the final? 

Thank you

**Comment by mikeizbicki** [comment]
> Will the final be over writing SQL queries or like the questions in the practice final pdf on github?

I believe the grading section immediately below what you quoted answers this questrion.  In particular, 4/20 points are for writing the SQL queries, and 16/20 points are for discussing how to make those queries fast.

> I noticed that the practice problems do not have JOIN commands.

Each of the 5 practice problem sheets has SQL queries that use JOIN.  For example, the 2023 final exam includes JOINs in problem 4 and 5.

> Other than reading the articles, how else do you recommend studying for the final?

Because 16/20 of the points come from the answering problems similar to the practice problems, I recommend being able to solve the practice problems.  If you can't solve the practice problems, you won't do well on the final.

I will also be available Monday during the normal office hours timeslot from 9:30-11am for final related questions.

**Comment by luisgomez214** [comment]
Thank you for the clarification!
