### ISSUE TITLE
github test actions expectations

### ISSUE THREAD

**Issue by myngpog** [mikeizbicki/cmc-csci143#564]
hi im wondering if we only need to test whether our docker stuff builds successfully with github actions. do we need to test whether or not our db is loaded?

**Comment by adamzterenyi** [comment]
Your database will have to start up because the action has to try and load data into it. However, it will only start up locally for GitHub. If you get your ports working for your development environment on your own computer (when you only run `$ docker-compose up --build`), this should work seamlessly. Next, you'll need to run your data insertion file on the test file you've given GitHub actions, which is just like calling a `.sh` file. I hope I could answer your question.

**Comment by myngpog** [comment]
yeah it clarified things for me , thanks!
