### ISSUE TITLE
Unable to connect to the server (Week 11 Hwrk) 

### ISSUE THREAD

**Issue by cduong21** [mikeizbicki/cmc-csci143#60]
![image](https://user-images.githubusercontent.com/54452916/116172906-744bfa00-a6c0-11eb-91d5-629bd1476b7b.png)

I am attempting to run `load_tweets.sh`. I have changed the ports in the .yml file and made the respective changes in the .sh file as well. I also made the change so that the script runs postgresql instead of postgres (for the --db argument). 

I keep running into this issue, and it's too specific for googling the error message. Would appreciate any help! :)

**Comment by mikeizbicki** [comment]
Hmm... port issues would be what I'd have guessed as the most likely culprit, but you've already checked that... have you double checked that the containers are running with the `docker ps` command?  That should be the only two things you have to do in order to connect.

If that doesn't fix the problem, I'd reclone the repo because maybe you accidentally modified a file somewhere that is causing things to not work.

**Comment by cduong21** [comment]
Recloned the repo, I must have mistakenly deleted something! Thank you.
