### ISSUE TITLE
Task 2: loading data: 'Rate limit exceeded'

### ISSUE THREAD

**Issue by afzal-p** [mikeizbicki/cmc-csci143#65]
I am running the command:
`./downloader_warc.sh https://commoncrawl.s3.amazonaws.com/CC-MAIN-2021-17/warc.paths.gz`

to start a new docker container connected to the database, but am running into the following rate limit exceeded error:

<img width="1276" alt="Screen Shot 2021-04-30 at 3 02 21 PM" src="https://user-images.githubusercontent.com/36056734/116748598-4cf97380-a9c5-11eb-87a4-df15cb8605da.png">

**Comment by BrandontMitchell** [comment]
+1 also getting the same error. I believe my url was correct as well but also getting access denied locally for novichenko/downloader_warc

**Comment by mikeizbicki** [comment]
Github rate limits requests by ip address.  Since everyone on the lambda server is using the same ip address, it's counting everyone's activity as part of the limitation.  If you wait a few minutes (and no one else from class makes a similar request), then the error should go away.  After you've successfully built the system once, you won't run into this issue again.

**Comment by afzal-p** [comment]
> Github rate limits requests by ip address. Since everyone on the lambda server is using the same ip address, it's counting everyone's activity as part of the limitation. If you wait a few minutes (and no one else from class makes a similar request), then the error should go away. After you've successfully built the system once, you won't run into this issue again.

I have been trying to build the system, but now I am having trouble with bash:
`-bash: cannot create temp file for here-document: Disk quota exceeded` 
Do you have suggestions for clearing up space?

edit: I found the command `$du -hd1` here (https://github.com/mikeizbicki/cmc-csci143/issues/8) helpful
