### ISSUE TITLE
Container name already in use

### ISSUE THREAD

**Issue by CurtisSalinger** [mikeizbicki/cmc-csci143#66]
When I go in and try to download another WARC files, I am met with the error 

```
The container name "/metahtml_warc_crawl-data" is already in use by container "b5e202ea78cf808cd9d6ce649bb9547b2fee256dd2e355bd9561d05fd92ced82".  You have to remove (or rename) that container to be able to reuse that name
```

I think a few others have had the same issue as well, is removing the container the right move here? or how else can we load all of the different WARC files?

Thanks!

**Comment by mikeizbicki** [comment]
The name of the container is the name of the warc file being downloaded.  Since you're downloading different warc files with each container, they should have different names.  What I'm guessing is happening (based on your container name) is that the url you are providing is not the url to a warc file, but something else.  My guess is that if you run
```
$ docker logs b5e202ea78cf808cd9d6ce649bb9547b2fee256dd2e355bd9561d05fd92ced82
```
you'll see an error message about the url being incorrect.

**Comment by CurtisSalinger** [comment]
I did receive a 404 error when I ran `docker logs`.

The code I used to download was  
```
$ ./downloader_warc.sh https://commoncrawl.s3.amazonaws.com/s3://commoncrawl/crawl-data/CC-MAIN-2020-34
```
 I thought this was in the format we are supposed to use, but is this incorrect?

**Comment by nguyenank** [comment]
I'm also getting that error that Curtis is, but I've confirmed via `psql` that things are getting inserted but when trying to run things in parallel I still get the error that all containers have the name, for me, `metahtml_warc_warc`.

**Comment by mikeizbicki** [comment]
@CurtisSalinger The URL you are passing into `downloader_warc.sh` should be a valid url that you can use to download the warc file in firefox.  If you type that into firefox, you'll see it won't work.  There's two problems: the `s3://` should not be in the middle of your url, and the end of the url should look something like `.warc.gz` to correspond to a warc file.

@nguyenank The `docker ps` command only shows an abbreviated version of the name due to space issues.  So while it may appear they have the same name, it's only the first 20 characters or so that are the same.

**Comment by nguyenank** [comment]
That makes sense, but I still get the following error:

```
The container name "/metahtml_warc_warc" is already in use by container "68fcc69ff2d0f75cabc26cbe59048fd010666ec694cdd28a252bfbf124678a83". You have to remove (or rename) that container to be able to reuse that name.
```

But then when I remove that container (I've just been running things sequentially for now), then my new container starts perfectly fine and things get inserted according to the `psql` query.

**Comment by mlaugharn** [comment]
I think the name variable in downloader_warc.sh is being reset to warc. I just used a random string instead for the name:

`NEW_UUID=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)`

` docker run -d --name=metahtml_warc_$NEW_UUID --network=novichenko novichenko/downloader_warc --db=postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@db:5432/$POSTGRES_DB "--warc=$warc"`
