### ISSUE TITLE
Step 2a - Disk quota exceeded

### ISSUE THREAD

**Issue by hwing777** [mikeizbicki/cmc-csci143#68]
I'm trying to load the WARC files in step 2a, but it stops at STEP 10/14 with a Disk quota exceeded error. 

![image](https://user-images.githubusercontent.com/39741440/116796266-2ca2e500-aaa9-11eb-96e1-a6039459c8d8.png)

This seems to be pretty similar to an issue mentioned in [#65](https://github.com/mikeizbicki/cmc-csci143/issues/65#issuecomment-830537477), where `$du -hd1` lists large folders that could be deleted, but I only have one folder `./.local/share/docker/overlay2` taking up 12G of space. I've tried `docker system prune` which seems to temporarily help (clears up ~2G each time) but it doesn't seem to be enough for the WARC files. Is there some other reason the disk quota issue is happening?

**Comment by afzal-p** [comment]
I am also now running into this issue. My .local directory is the largest at 12gb, but there are still disk quota errors.

**Comment by mikeizbicki** [comment]
It's possible to complete the assignment with your original 10GB disk space allotment, you just have to be careful with what you're putting where.  Note that running `docker system prune` does not delete all docker resources, only those that are not currently in use.  So you have to explicitly stop/delete your running containers before pruning for the command to have an effect on them.

That said, I've increased the disk space allotments for everyone in class to 20GB, so that should make it a bit easier to manage the resources.

**Comment by hwing777** [comment]
I think that I've realized the problem we've been running into. I originally downloaded the WARC file incorrectly, and tried to load the full file with a URL in the form
`https://commoncrawl.s3.amazonaws.com/crawl-data/CC-MAIN-2021-17`
or
`https://commoncrawl.s3.amazonaws.com/crawl-data/CC-MAIN-2015-06/warc.paths.gz`

However this links to the wrong folder. Instead, you need to download the WARC file, unzip it (I'm on Windows and used WinZip), and use the links stored there. They should be in the format
`https://commoncrawl.s3.amazonaws.com/crawl-data/CC-MAIN-2021-17/segments/1618038056325.1/warc/CC-MAIN-20210416100222-20210416130222-00000.warc.gz`
I found it helpful to follow along carefully with the lecture from 2021-04-26.

I took down all of my containers and ran `docker system prune` to make sure I cleared out enough space from my previous mistakes. The disk space increase to 20GB seems to be enough and I haven't run into more space errors.
