### ISSUE TITLE
Search terms not appearing in search engine

### ISSUE THREAD

**Issue by anan-ara** [mikeizbicki/cmc-csci143#74]
I have just finished adding the 5 warc files to the database and the results of `SELECT count(*) FROM metahtml;` show that they have been added successfully, but my search engine still shows 0 search results for all the search term's I've tested.

**Comment by mikeizbicki** [comment]
Hmm... there's a good chance that you're not inserting into the metahtml table correctly.  Just because a row appears and is registered by `COUNT(*)` doesn't mean you've properly inserted into the table.

For example, you can use a query like
```
SELECT unnest(tsvector_to_array(title)) AS word, count(*) FROM metahtml GROUP BY word ORDER BY count DESC;
```
to get the most commonly used words and search for those.  If you've correctly inserted, there should be a LOT of words returned by the above query.

**Comment by anan-ara** [comment]
The issue was that my pspacy_content variable was wrong. I have fixed it now. Thank you!
