### ISSUE TITLE
Passing /ngrams but not the other two

### ISSUE THREAD

**Issue by valenxie** [mikeizbicki/cmc-csci143#75]
My webpage runs fine but check_web_endpoints.sh is not fully passing, any suggestions on that? I did the steps that Curtis mentioned in his post and right now I'm not sure where the issue is coming from.

**Comment by valenxie** [comment]
I realized I didn't rebuild the images after git submodule init so I removed all containers/images and rebuilt the container, right now all three won't pass even with docker-compose.yml and check_web_endpoints.sh changed

**Comment by valenxie** [comment]
Along the way, I also recloned the folder but when building it an error came up saying something like the port is already been used, so I switched to another one. I don't know if that caused some trouble, http://localhost:8080/ still works fine

**Comment by valenxie** [comment]
I successfully built the containers for each url but when running docker log it shows "ERROR:  pgbouncer cannot connect to server"

**Comment by mikeizbicki** [comment]
Hmmm.... in the future you'll want to include the full output of logs in github issues.  Just one snippet isn't very much to go on.

My best guess is that the `pg` instance was not started successfully, and that's why the `db` instance cannot connect to it.  You'll have to check the logs of `pg` to see why that might be the case.

**Comment by valenxie** [comment]
<img width="1440" alt="截屏2021-05-11 上午12 50 58" src="https://user-images.githubusercontent.com/38342307/117695867-46ec6980-b1f3-11eb-88b7-38f449d02655.png">
Here is the result of running docker logs on search engine pg, but I'm not exactly sure what might be leading to this error.

**Comment by mikeizbicki** [comment]
You can see that the logs state that `database "novichenko" does not exist`.  This means that my hypothesis

> My best guess is that the pg instance was not started successfully, and that's why the db instance cannot connect to it. 

was correct.  The database likely was not successfully created because you did not initialize the git submodules after cloning the repo.  (You have stopped/restarted your db instance, however, so you've erased the logs of what caused the db not to be created correctly.)

In order to fix the problem, you'll have to:
1. change the location of the docker volume where the db is stored (so that a new db cluster can be created)
2. rebuild your docker images
3. bring up your docker containers (this will try to create the database)
4. if the database is not created successfully, view the logs (before you bring the db down) to diagnose why the db did not start successfully, and repeat from step 1

**Comment by valenxie** [comment]
Thanks for the advice. I modified the location, removed previous images, and successfully rebuilt everything, there seem to be the same errors. The first screenshot is the logs on search_engine_web_1 and the second is on search_engine_db_1/
<img width="1440" alt="截屏2021-05-13 下午11 29 03" src="https://user-images.githubusercontent.com/38342307/118148534-3e8a6d80-b443-11eb-9cce-81d33d285992.png">

<img width="1440" alt="截屏2021-05-13 下午11 24 03" src="https://user-images.githubusercontent.com/38342307/118148453-29154380-b443-11eb-9031-3602ef168227.png">
I can't quite figure out why it failed to connect to novichenko.

**Comment by valenxie** [comment]
<img width="1440" alt="截屏2021-05-14 上午3 51 06" src="https://user-images.githubusercontent.com/38342307/118179274-a488ec00-b467-11eb-94f9-17d98b415a0b.png">
I repeated the steps on a new cloned repo and now the logs of the containers seem to be fine but still not passing when checking the endpoints:(

**Comment by valenxie** [comment]
Hi Mike@mikeizbicki, I repeated all steps on a new cloned repo and the logs of the containers seemed to be fine while still failing the checkendpoints tests(shown in picture), then my laptop got super slow and hardly respond to anything so I had to log in to lambda server again after around half an hour since it got disconnected, then when I docker ps there were only two containers so I brought up the other container, however this time the logs are showing the same errors I encountered before...
<img width="1440" alt="截屏2021-05-14 上午3 51 06" src="https://user-images.githubusercontent.com/38342307/118179892-7657dc00-b468-11eb-9468-6c68470cdf91.png">

**Comment by mikeizbicki** [comment]
You should be checking the logs of the postgres server (`pg` service in docker-compose), since this is what's failing.  You are only checking the logs of the pg_bouncer server (`db` in docker-compose), so that's why you're not able to see the reason that it's failing.

Depending on the commands you've run, the logs may have been deleted, and you may need to repeat those steps again in order to see the logs.

**Comment by valenxie** [comment]
Hi Mike@mikeizbicki , I think I did check the logs of both pg and db but here is the screen shot of running docker logs on search_engine_pg_1 (is this what I'm supposed to do..?)and it only pointed out that database system was interrupted(pic1). Then I built and brought up the containers again after changing the volumn location the logs then seem fine(pic2), but tests still fail. Opening up psql also returns "psql: error: could not connect to server: No such file or directory" which I googled and says might be caused by firewall issue..
<img width="1166" alt="截屏2021-05-14 下午12 01 24" src="https://user-images.githubusercontent.com/38342307/118220447-4d5a3a00-b4ae-11eb-8f94-cba456ecede2.png">
<img width="1440" alt="截屏2021-05-14 下午12 15 16" src="https://user-images.githubusercontent.com/38342307/118220898-441d9d00-b4af-11eb-9fa1-f84dd17788e4.png">
