### ISSUE TITLE
Disk Quota Exceeded 

### ISSUE THREAD

**Issue by cduong21** [mikeizbicki/cmc-csci143#77]
Hi Mike, I think I saw this error before because there were too many forked processes. I'm unable to use tab completion/ cd into directories haha :( 
 
![image](https://user-images.githubusercontent.com/54452916/117704253-7b264280-b17f-11eb-9db6-4097f88bfb8b.png)

Could you terminate them from your end? Thank you!

**Comment by asapirstein** [comment]
I was getting this error when I tried to run too many of the warc_loader containers in parallel - you can probably list all of the docker images and just stop and delete some of them to free up some memory

**Comment by cduong21** [comment]
Ahhhh, I'm in a little too deep... I can't run `docker ps` or any other command anymore :/ But thank you for the suggestion!!

**Comment by mikeizbicki** [comment]
@cduong21 You will have to find out what is consuming so much of your disk space and delete it.  Docker images and containers are the most likely culprits for consuming lots of disk space (`docker system df --verbose` with give you a list of all the resources docker is consuming), but if you're not able to start docker due to disk space problems, you'll have to delete other files/folders manually with the `rm` command.  You can use the `du -hd0` and `ls -l` commands to find which files/folders are consuming too much space.
