### ISSUE TITLE
Trouble Installing Rootless Docker

### ISSUE THREAD

**Issue by dustin-lind** [mikeizbicki/cmc-csci143#95]
Hi Mike,

I'm trying to install a rootless docker through my terminal using the instructions on [Docker Docs](https://docs.docker.com/engine/security/rootless/#install). 

First I tried running
```
 $ dockerd-rootless-setuptool.sh install
```
but I got the error
```
dockerd-rootless-setuptool.sh: command not found
```
Then I tried running 
```
 $ sudo apt-get install -y docker-ce-rootless-extras
```
because the documentation says that I should run this if If `dockerd-rootless-setuptool.sh` is not present. I get prompted:
```
[sudo] password for Dustin.Lind.22:
```
I'm not sure what my password would be, so I just tried typing in my password to the lambda server, but I get the error
```
Dustin.Lind.22 is not in the sudoers file.  This incident will be reported.
```

Also, would you mind going over at the start of the class how to do step ii of the install rootless docker? You wrote 

1. move the contents of the `bin` folder into `.local/bin`
2. add the `DOCKER_HOST` environment variable to your `.bashrc` file

but I'm not sure how to do this.

Best,

Dustin

**Comment by mikeizbicki** [comment]
The `sudo` command is for running commands as the `root` (i.e. admin) user, and you don't have permissions for that.  That's why that command isn't working.

In the link you provided, there's a tab labeled `Without packages`.  You'll want to click on that tab and follow those instructions, since you don't have access to the `dockerd-rootless-setuptool.sh` command.  This is admittedly not very well labeled in their instructions.

> Also, would you mind going over at the start of the class how to do step ii of the install rootless docker? 

Certainly!

**Comment by dustin-lind** [comment]
Thanks for the help!

**Comment by Bhargavaa1** [comment]
Hi Mike and Dustin,
I attempted to install Rootless Docker by following the instructions on the ```Without packages``` tab but I ran into this error when using the given [installation script](https://get.docker.com/rootless): ```Rootless Docker cannot be installed on Darwin```. Have either of you ran into the error before?

Thanks,
Adi

**Comment by mikeizbicki** [comment]
@Bhargavaa1 Darwin is the name of the Mac operating system, so that makes me think you're installing it locally on your laptop.  You should install it on your lambda server account.

**Comment by Bhargavaa1** [comment]
Ok thanks for the clarification.

**Comment by iamasteriix** [comment]
I can only run `docker` commands once for some reason after which I have to reinstall rootless docker again, every single time!

Running `systemctl status docker` throws the error `Unit docker.service could not be found`.

I noticed this warning message in my install logs though, and I am not sure if it has anything to do with this:
```
[WARNING] File already exists, skipping: /home/myusername/.config/systemd/user/docker.service
```

**Comment by mikeizbicki** [comment]
@ceejay-el hmm... that's weird and shouldn't happen.  I'll need to see the exact sequence of commands and their outputs in order to help.

In general, it's always better to over report information than try to truncate error messages down to what you think is the problem and report only that.  Even if it's pages and pages of logs.

**Comment by iamasteriix** [comment]
Not sure if this is going to help anyone in future, but I just stepped away from my computer for about 2 hours and everything was fine when I came back.

Also, I figured that the error message `Unit docker.service could not be found` was probably caused by me running a root user command. The more appropriate command would be
```
systemctl --user status docker
```

**Comment by iamasteriix** [comment]
I just saw this message while building my docker image and was wondering whether I should be worried:

```
ApplyLayer exit status 1 stdout:  stderr: write /usr/lib/python2.7/lib2to3/fixes/fix_tuple_params.py: disk quota exceeded
```
